<?php
if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_630787244d8d6',
		'title' => 'Характеристики объекта недвижисти',
		'fields' => array(
			array(
				'key' => 'field_6307874111fa4',
				'label' => 'Площадь',
				'name' => 'square',
				'type' => 'number',
				'instructions' => 'Введите общую площадь вашей недвижимости',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 44,
				'prepend' => 'Площадь',
				'append' => 'м2',
				'min' => 0,
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_6307882911fa6',
				'label' => 'Стоимость',
				'name' => 'price',
				'type' => 'number',
				'instructions' => 'Введите предполагаемую стоимость	недвижимости',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 4400000,
				'prepend' => 'Стоимость',
				'append' => 'руб',
				'min' => 0,
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_630788a411fa8',
				'label' => 'Адрес',
				'name' => 'address',
				'type' => 'text',
				'instructions' => 'Введите адрес недвижимости',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Адрес',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_630788e311faa',
				'label' => 'Жилая площадь',
				'name' => 'living_area',
				'type' => 'number',
				'instructions' => 'Введите жилую площадь недвижимости',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 40,
				'prepend' => 'Жилая площадь',
				'append' => 'м2',
				'min' => 0,
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_6307896311fab',
				'label' => 'Этаж',
				'name' => 'floor',
				'type' => 'number',
				'instructions' => 'Введите этаж',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 3,
				'prepend' => 'Этаж',
				'append' => '',
				'min' => 0,
				'max' => '',
				'step' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'property',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

endif;